<?php
namespace app\admin\common;
use think\Controller;
use think\Session;

class Base extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        define('USER_ID',Session::get('user_id'));
    }

    //判断用户是否登录，在后台入口调用
    protected function isLogin(){
        if(is_null(USER_ID)){
            $this ->error('检测到您还未登录，请先登录','login/index');
        }
    }

    //如果已经登录，判断是否重复登录
    protected function alreadyLogin(){
//        if(!is_null(USER_ID)){
//            $this ->error('请不要重复登录','login/index');
//        }
    }
}